FROM golang:1.18

ARG GOOS
ARG GOARCH
ENV GOOS ${GOOS}
ENV GOARCH ${GOARCH}

RUN curl -f https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

RUN mkdir -p /go/src/github.com/cloudwm/cli
WORKDIR /go/src/github.com/cloudwm/cli
